name = "EnergyBalanceModel"
uuid = "68dbb056-390c-4f33-8773-0304cbd749ae"
version = "0.4.0"
authors = ["Waylon Wu <me@waylonwu.net>", "Navid C. Constantinou <navidcy@users.noreply.github.com>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[extensions]
CairoExt = "CairoMakie"
OpenGLExt = "GLMakie"
WebGLExt = "WGLMakie"

[compat]
CairoMakie = "0.15.6"
Dates = "1.10.10"
GLMakie = "0.13.6"
JLD2 = "0.6.2"
LinearAlgebra = "1.10.10"
Makie = "0.24.6"
NonlinearSolve = "4.12.0"
SparseArrays = "1.10.0"
Statistics = "1.10.0"
StyledStrings = "1.0.3"
TimeZones = "1.22.1"
UUIDs = "1.10.10"
WGLMakie = "0.13.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
